// @generated by dsync
#![allow(clippy::all)]
#![allow(unused_imports)]

//! Database model modules generated from the Diesel schema.

use diesel::prelude::*;

/// User-related models.
pub mod users;
