name: CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://user:password@localhost/dummy

jobs:
  build_and_test:
    name: Build, Test & Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup override set stable
          rustup component add rustfmt
          rustup component add clippy
          rustup target add wasm32-unknown-unknown

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev make

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Clippy (Linting)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Build Workspace
        run: cargo build --verbose --workspace --all-targets

      - name: Build WASM
        run: |
          make build_wasm

      - name: Run Tests
        run: cargo test --verbose --workspace

      - name: Download Petstore Specs
        run: |
          curl -sSL https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml -o petstore_oas3.yaml
          # Download a standard swagger 2.0 petstore
          curl -sSL https://petstore.swagger.io/v2/swagger.json -o petstore.json

      - name: Test Swagger 2.0 Petstore SDK Generation
        run: cargo run -p cdd-cli -- from_openapi to_sdk -i ./petstore.json -o ./target/petstore2

      - name: Test OpenAPI 3.2.0 Petstore SDK Generation
        run: cargo run -p cdd-cli -- from_openapi to_sdk -i ./petstore_oas3.yaml -o ./target/petstore3

      - name: Check Documentation Coverage
        run: |
          rustup toolchain install nightly
          RUSTDOCFLAGS="-Z unstable-options --show-coverage" cargo +nightly doc --workspace --no-deps

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Test Coverage
        # Ignoring fail under 100 for now as current codebase might not be 100%
        run: cargo tarpaulin --workspace --out Xml

      - name: Upload artifacts (if tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/cdd-rust
